#!/bin/bash

count=0

# Loop until counter reaches 10
while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
