#!/usr/bin/env bash
# Displays information about the `school` file.

file="school"

if [ -e "$file" ]; then
  echo "$file exists"
  if [ -s "$file" ]; then
    echo "$file is not empty"
  else
    echo "$file is empty"
  fi

  if [ -f "$file" ]; then
    echo "$file is a regular file"
  elif [ -d "$file" ]; then
    echo "$file is a directory"
  else
    echo "$file is neither a regular file nor a directory"
  fi
else
  echo "$file does not exist"
fi

